{
 "title": "Istio Galley Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Event Rates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Events/min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(galley_runtime_strategy_on_change_total[1m])) * 60",
     "legendFormat": "Strategy Change Events"
    },
    {
     "expr": "sum(rate(galley_runtime_processor_events_processed_total[1m])) * 60",
     "legendFormat": "Processed Events"
    },
    {
     "expr": "sum(rate(galley_runtime_processor_snapshots_published_total[1m])) * 60",
     "legendFormat": "Snapshot Published"
    }
   ]
  },
  {
   "title": "Timer Rates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Events/min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(galley_runtime_strategy_timer_max_time_reached_total[1m])) * 60",
     "legendFormat": "Max Time Reached"
    },
    {
     "expr": "sum(rate(galley_runtime_strategy_timer_quiesce_reached_total[1m])) * 60",
     "legendFormat": "Quiesce Reached"
    },
    {
     "expr": "sum(rate(galley_runtime_strategy_timer_resets_total[1m])) * 60",
     "legendFormat": "Timer Resets"
    }
   ]
  },
  {
   "title": "Events Per Snapshot",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (galley_runtime_processor_snapshot_events_total_bucket))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (galley_runtime_processor_snapshot_events_total_bucket))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (galley_runtime_processor_snapshot_events_total_bucket))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (galley_runtime_processor_snapshot_events_total_bucket))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "State Type Instances",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum by (typeURL) (galley_runtime_state_type_instances_total)",
     "legendFormat": "{{ typeURL }}"
    }
   ]
  },
  { "title": "Validation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Validation Webhook Certificate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "galley_validation_cert_key_updates{job=\"galley\"}",
     "legendFormat": "Key Updates"
    },
    {
     "expr": "galley_validation_cert_key_update_errors{job=\"galley\"}",
     "legendFormat": "Key Update Errors: {{ error }}"
    }
   ]
  },
  {
   "title": "Resource Validation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(galley_validation_passed{job=\"galley\"}) by (group, version, resource)",
     "legendFormat": "Passed: {{ group }}/{{ version }}/{{resource}}"
    },
    {
     "expr": "sum(galley_validation_failed{job=\"galley\"}) by (group, version, resource, reason)",
     "legendFormat": "Failed: {{ group }}/{{ version }}/{{resource}} ({{ reason}})"
    }
   ]
  },
  {
   "title": "Validation HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(galley_validation_http_error{job=\"galley\"}) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  { "title": "Kubernetes Source", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Source Event Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Events/min" }
   ],
   "targets": [
    {
     "expr": "rate(galley_kube_source_listener_handle_event_success_total[1m]) * 60",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(galley_kube_source_listener_handle_event_error_total[1m]) * 60",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Kubernetes Object Conversion Successes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Conversions/min" }
   ],
   "targets": [
    {
     "expr": "rate(galley_kube_source_source_converter_success_total[1m]) * 60",
     "legendFormat": "{apiVersion=\"{{apiVersion}}\",group=\"{{group}}\",kind=\"{{kind}}\"}"
    }
   ]
  },
  {
   "title": "Kubernetes Object Conversion Failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Failures/min" }
   ],
   "targets": [
    {
     "expr": "rate(galley_kube_source_source_converter_failure_total[1m]) * 60",
     "legendFormat": "Error"
    }
   ]
  },
  { "title": "Mesh Configuration Protocol", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Connected Clients",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(galley_mcp_server_clients_total)",
     "legendFormat": "Clients"
    }
   ]
  },
  {
   "title": "Request ACKs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "ACKs/min" }
   ],
   "targets": [
    {
     "expr": "rate(galley_mcp_server_request_acks_total[1m]) * 60"
    }
   ]
  },
  {
   "title": "Request NACKs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "NACKs/min" }
   ],
   "targets": [
    {
     "expr": "rate(galley_mcp_server_request_nacks_total[1m]) * 60"
    }
   ]
  }
 ]
}